<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.5</version>
        <relativePath/>
    </parent>

    <groupId>org.mobilecms</groupId>
    <artifactId>mobilecms-api-java</artifactId>
    <version>50.0.0-SNAPSHOT</version>
    <name>mobilecms-api-java</name>
    <description>REST API for JSON-file content, authentication, media, and administration</description>

    <properties>
        <java.version>21</java.version>
        <nimbus.version>9.47</nimbus.version>
        <thumbnailator.version>0.4.21</thumbnailator.version>
        <pdfbox.version>3.0.5</pdfbox.version>
        <springdoc.version>2.8.9</springdoc.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>${nimbus.version}</version>
        </dependency>
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
            <version>${thumbnailator.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.9.0</version>
                <executions>
                    <execution>
                        <id>generate-admin-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi-adminapi.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.basedir}/src/generated/admin</output>
                            <sourceFolder>src/main/java</sourceFolder>
                            <apiPackage>org.mobilecms.generated.admin.api</apiPackage>
                            <modelPackage>org.mobilecms.generated.admin.model</modelPackage>
                            <invokerPackage>org.mobilecms.generated.admin</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-auth-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi-authapi.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.basedir}/src/generated/auth</output>
                            <sourceFolder>src/main/java</sourceFolder>
                            <apiPackage>org.mobilecms.generated.auth.api</apiPackage>
                            <modelPackage>org.mobilecms.generated.auth.model</modelPackage>
                            <invokerPackage>org.mobilecms.generated.auth</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-cms-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi-cmsapi.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.basedir}/src/generated/cms</output>
                            <sourceFolder>src/main/java</sourceFolder>
                            <apiPackage>org.mobilecms.generated.cms.api</apiPackage>
                            <modelPackage>org.mobilecms.generated.cms.model</modelPackage>
                            <invokerPackage>org.mobilecms.generated.cms</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-file-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi-fileapi.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.basedir}/src/generated/file</output>
                            <sourceFolder>src/main/java</sourceFolder>
                            <apiPackage>org.mobilecms.generated.file.api</apiPackage>
                            <modelPackage>org.mobilecms.generated.file.model</modelPackage>
                            <invokerPackage>org.mobilecms.generated.file</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-web-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi-webapi.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.basedir}/src/generated/web</output>
                            <sourceFolder>src/main/java</sourceFolder>
                            <apiPackage>org.mobilecms.generated.web.api</apiPackage>
                            <modelPackage>org.mobilecms.generated.web.model</modelPackage>
                            <invokerPackage>org.mobilecms.generated.web</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-misc-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/openapi-miscapi.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <output>${project.basedir}/src/generated/misc</output>
                            <sourceFolder>src/main/java</sourceFolder>
                            <apiPackage>org.mobilecms.generated.misc.api</apiPackage>
                            <modelPackage>org.mobilecms.generated.misc.model</modelPackage>
                            <invokerPackage>org.mobilecms.generated.misc</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useJakartaEe>true</useJakartaEe>
                                <useSpringBoot3>true</useSpringBoot3>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <serializableModel>true</serializableModel>
                                <useTags>true</useTags>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>add-generated-java-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.basedir}/src/generated/admin/src/main/java</source>
                                <source>${project.basedir}/src/generated/auth/src/main/java</source>
                                <source>${project.basedir}/src/generated/cms/src/main/java</source>
                                <source>${project.basedir}/src/generated/file/src/main/java</source>
                                <source>${project.basedir}/src/generated/web/src/main/java</source>
                                <source>${project.basedir}/src/generated/misc/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

